<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_star text-warning fa fa-star</name>
   <tag></tag>
   <elementGuidId>0870ca97-51e9-4494-8194-e3fc6d976d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;go-right&quot;]/label[@for='4']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;go-right&quot;]/label[@for='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star text-warning fa fa-star voted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;go-right&quot;]/label[@for='4']</value>
   </webElementProperties>
</WebElementEntity>
