<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_icon-calendar</name>
   <tag></tag>
   <elementGuidId>9cfa1d56-6fd2-458a-98e4-6a8bbdab8475</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-calendar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscription_form&quot;)/div[1]/fieldset[@class=&quot;module aligned  module_0 initialized&quot;]/div[@class=&quot;form-row field-start_date&quot;]/div[1]/a[@class=&quot;vDateField-link&quot;]/span[@class=&quot;icon-calendar&quot;]</value>
   </webElementProperties>
</WebElementEntity>
