<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Account</name>
   <tag></tag>
   <elementGuidId>979286e6-8984-4b7b-b26b-5e25341f78fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;collapse&quot;)/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-side navbar-right sidebar go-left&quot;]/li[@class=&quot;open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[@class=&quot;go-text-right&quot;][count(. | //a[@href = 'https://www.phptravels.net/account/' and (text() = '  Account' or . = '  Account')]) = count(//a[@href = 'https://www.phptravels.net/account/' and (text() = '  Account' or . = '  Account')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>go-text-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.phptravels.net/account/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse&quot;)/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-side navbar-right sidebar go-left&quot;]/li[@class=&quot;open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[@class=&quot;go-text-right&quot;]</value>
   </webElementProperties>
</WebElementEntity>
